#!/bin/bash
# Yeah, idk why I made that exitStatement instead of closing or some
echo -e "= Are you sure you want to leave? =\n[Yes]\n[No]\n"
read -p ">> " userInput
echo -e "\n"
case "$userInput" in
    yes|Yes|YES )
        clear
        exit
        ;;
    no|No|NO )
        clear
        source /home/jstrayer8477/mainMenu
        ;;

    * )
        printf "\n= Uh oh :O =\n"
        ;;
esac
