#!/bin/bash
# This is the main menu script
echo -e "\n[Main Menu]\n\n"
echo -e "[Riddle?]\n[Quit?]\n[About?]"
read -p ">> " userInput
echo -e "\n"
case "$userInput" in
    Riddles|riddles|RIDDLES|riddle|Riddle|RIDDLE )
        source /home/jstrayer8477/riddles
        ;;
    Quit|quit|QUIT )
        source /home/jstrayer8477/exitStatement
        ;;
    about|About|ABOUT )
        source /home/jstrayer8477/aboutScreen
        ;;
    * )
        echo -e ":/ This was not an option\n\n"
        source /home/jstrayer8477/mainMenu
        ;;
esac
