#!/bin/bash
RANDOM=$$
clear
echo "----------------------"
echo -ne ":O               (00%)\r"
sleep 0.2
echo -ne "#####            (33%)\r"
sleep $(($RANDOM%5))
echo -ne "##########       (67%)\r"
sleep $(($RANDOM%4))
echo -e "###############  (100%)"
echo "----------------------"
sleep $(($RANDOM%3))
# riddleCounter=0 will be used to calculate how many riddles the player has done
echo -e "Would you like a riddle? :)\n"
echo -e "[Yes]\n[No]\n"
read -p ">> " response
echo -e "\n"
case "$response" in
    yes|Yes|YES )
        echo -e "Perfect!\n"
        echo -e "For your first riddle\nWhat is a household pet, meows, and reveals the contents of a file?\m"
        echo -e "Remember! This language is case sensitive and all of the riddles asked result in commands that are all lower case!\nYou have been warned :)"
        read -p ">> " riddle01
        case "$riddle01" in
            cat )
                echo -e "Yep! You got it right! That one was pretty easy right?\n"
                ;;
            help|Help|HELP )
                echo -e "Sorry, this hasn't been implemented yet. :P\n"
                ;;
            * )
                echo -e "Uh oh spaghetti-os\nA mistake sends you back to the start of the riddles :)\n"
                source /home/jstrayer8477/LARK_Project/riddles
                ;;
        esac
        echo -e "For your second riddle\nWhat is the thirteenth letter of the Latin Alphabet? For the second letter, what is the abbreviation of 'Ok'?\n"
        read -p ">> " riddle02
        echo -e "\n"
        case "$riddle02" in
            mk )
                echo -e "Wow! You got it right!\n"
                ;;
            help|Help|HELP )
                echo -e "Help was implemented for this one! Try 13! Go back to the start though :)\n"
                source /home/jstrayer8477/LARK_Project/riddles
                ;;
            * )
                echo -e "Ye who shalt be cast once more unto the start!\n"
                source /home/jstrayer8477/LARK_Project/riddles
                ;;
        esac
        echo -e "It seems I will have to find harder riddles to ask you!\n"
    no|No|NO )
        echo -e "What are you doing here then?\n"
        echo "----------------------"
        echo -ne ":O               (00%)\r"
        sleep 0.2
        echo -ne "#####            (33%)\r"
        sleep $(($RANDOM%5))
        echo -ne "##########       (67%)\r"
        sleep $(($RANDOM%4))
        echo -e "###############  (100%)"
        echo "----------------------"
        sleep 1.5
        source /home/jstrayer8477/LARK_Project/mainMenu
        ;;
    * )
        echo -e "\nUh oh, that wasn't one of the prompted responses. Try again please\n"
        source /home/jstrayer8477/LARK_Project/riddles
        ;;
esac
clear
sleep $(($RANDOM%3))
echo "----------------------"
echo -ne ":O               (00%)\r"
sleep 0.2
echo -e "###############  (100%)"
echo "----------------------"
sleep 1
source /home/jstrayer8477/LARK_Project/mainMenu
